In [1]:
import numpy as np
arr1=np.array([6,2,-7,2,8,-2,1])
arr2=np.array([[1,3,5],[2,4,6]])

In [2]:
print(arr1.ndim)
print(arr2.ndim)
print(arr1.shape)
print(arr2.shape)
print(arr1.size)
print(arr2.size)
print(arr1.dtype)
print(arr2.dtype)

1
2
(7,)
(2, 3)
7
6
int64
int64


In [6]:
arr_all_0=np.zeros(6)
print(arr_all_0)
arr_all_1=np.ones(6)
arr_all_1

[0. 0. 0. 0. 0. 0.]


array([1., 1., 1., 1., 1., 1.])

In [7]:
print(arr_all_1)

[1. 1. 1. 1. 1. 1.]
