In [11]:
import numpy as np
arr1=np.array([1,3,2,4,9])
arr2=np.ones(5)
arr3=np.zeros(3)
arr4=np.concatenate([arr1,arr2,arr3])
arr4

array([1., 3., 2., 4., 9., 1., 1., 1., 1., 1., 0., 0., 0.])

In [13]:
np.sort(arr1)

array([1, 2, 3, 4, 9])

In [15]:
print(arr1[2])
print(arr1[-3])

2
2


In [18]:
arr1[1:4]

array([3, 2, 4])

In [19]:
arr1+arr2

array([ 2.,  4.,  3.,  5., 10.])

In [20]:
arr1*(-5)

array([ -5, -15, -10, -20, -45])

In [26]:
print(arr1.max())
print(arr1.min())
print(arr1.sum())
print(arr1.mean())

9
1
19
3.8


In [29]:
arr1[(arr1<1)|(arr1>3)]

array([4, 9])